# origin https://github.com/adrenak/upm-template/blob/master/.releaserc.json
# origin licensed under MIT License Copyright (c) 2020 Vatsal Ambastha
# origin license https://github.com/adrenak/upm-template/blob/master/LICENSE
# you can read more about how to use upm-template at https://github.com/adrenak/upm-template/

tagFormat: v${version}
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: angular
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - preset: angular
      changelogFile: Packages/NativeTrees/CHANGELOG.md
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: Packages/NativeTrees
  - - '@semantic-release/git'
    - assets:
        - Packages/NativeTrees/package.json
        - Packages/NativeTrees/CHANGELOG.md
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
  - '@semantic-release/github'
